---
include:
  - board: cosmos_lemon_wireless
    shield: rickballv4_left
  - board: cosmos_lemon_wireless
    shield: rickballv4_right vik_display_i2c
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: cosmos_lemon_wireless
    shield: settings_reset
