---
include:
  - board: cosmos_lemon_wireless
    shield: rickballv7_left
  - board: cosmos_lemon_wireless
    shield: rickballv7_right vik_pmw3610
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
