---
include:
  - board: cosmos_lemon_wireless
    shield: rickballv6_left vik_dsiuplay_i2c
  - board: cosmos_lemon_wireless
    shield: rickballv6_right vik_pmw3610
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
